### ISSUE TITLE
The `changed` in step `list-changed` will always be true

### ISSUE THREAD

**Issue by FushuWang** [helm/chart-testing-action#112] opened 2023-02-28 10:00 UTC
The output of `ct list-changed` will have other strings even if the chart is not changed.

```
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
```

```
Linting charts...
>>> helm version --template {{ .Version }}
>>> git rev-parse --is-inside-work-tree
>>> git merge-base origin/main HEAD
>>> git diff --find-renames --name-only c8b9381a98059c07b5b65510b8162c5df3f43cd0 -- charts
```

And those strings will make the `if check` always true. So that's why we will meet errors like this [issue](https://github.com/helm/chart-testing-action/issues/102).

**Comment by cpanato** [comment] 2023-03-24 10:45
not able to reproduce the issue, see my comment https://github.com/helm/chart-testing-action/issues/102#issuecomment-1482596871

closing this as not reproduced

**Closed by cpanato** 2023-03-24 10:45 UTC
