### ISSUE TITLE
chart-testing-action v2 failing to install pyyaml

### ISSUE THREAD

**Issue by JamieMagee** [helm/chart-testing-action#65] opened 2020-11-18 15:33 UTC
We're getting some python errors in our logs. Here's the excerpt:

```sh
Building wheels for collected packages: pyyaml
  Running setup.py bdist_wheel for pyyaml: started
  Running setup.py bdist_wheel for pyyaml: finished with status 'error'
  Complete output from command /opt/hostedtoolcache/ct/v3.3.0/x86_64/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-0n2ie3qi/pyyaml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp9srf5saopip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Running setup.py clean for pyyaml
  Failed building wheel for pyyaml
Failed to build pyyaml
```

You can see the [full log here](https://github.com/renovatebot/helm-charts/pull/84/checks?check_run_id=1411349444).

Looks like we're missing `wheel`?

**Comment by ohdearaugustin** [comment] 2020-11-18 16:56
I can confirm that use too.

**Comment by ohdearaugustin** [comment] 2020-11-18 17:06
@JamieMagee if you use ubuntu-latest the included python3 version is 3.6.9. That one is causing the problem. Try install python 3.7.0 as suggested in the Readme.

**Comment by JamieMagee** [comment] 2020-11-18 17:24
Thanks for the explanation.

It looks like this will solve itself when Ubuntu 20.04 becomes `ubuntu-latest`, as it ships with Python 3.8. See actions/virtual-environments#1816 for full details.

It would be nice to do a check in the chart-testing action and log a warning if the Python version is known to be too low. However, like I said above, it might be a moot point in a few weeks.

**Comment by tylerauerbeck** [comment] 2021-07-25 06:56
`ubuntu-latest` is now `ubuntu-20.04` so this shouldn't be an issue any longer and this can probably be closed.

**Comment by davidkarlsen** [comment] 2021-07-25 08:57
Closing since this is no longer a problem.

**Closed by davidkarlsen** 2021-07-25 08:57 UTC
